<?php

use common\models\Slider;

$sliders = Slider::find()->where(['status' => 'active'])->all();

?>
<!--Header end-->
<section class="position-relative p-0 no-transition" id="home">
    <h2 class="d-none">as</h2>
    <div id="rev_slider_18_1_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="megaone-medical-1" data-source="gallery" style="background:transparent;padding:0px;">
        <!-- START REVOLUTION SLIDER 5.4.8.1 fullscreen mode -->
        <div id="rev_slider_18_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.4.8.1">

            <ul>
                <?php foreach ($sliders as $key => $slider) : ?>

                    <!-- SLIDE  -->
                    <li data-index="rs-<?= 44 + $key ?>" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="assets/100x50_3d469-bg-light-1.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                        <!-- MAIN IMAGE -->
                        <img src="<?= $slider->backgroundimg ?>" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                        <div class="small-bg-overlay"></div>
                        <!-- LAYERS -->
                        <?php if ($key % 2 == 0) : ?>
                            <!-- LAYER NR. 1 -->
                            <div class="tp-caption   tp-resizeme" id="slide-44-layer-2" data-x="['<?= $slider->position ?>','<?= $slider->position ?>','center','center']" data-hoffset="['0','100','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-120','-120','-120','-96']" data-fontsize="['36','36','28','23']" data-lineheight="['46','46','38','33']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":270,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; margin-left:30%; white-space: nowrap; font-size: 36px; line-height: 46px; font-weight: 500; color: Black;   letter-spacing: 0px;font-family:Poppins;"><?= $slider->title ?></div>
                            <!-- LAYER NR. 2 -->
                            <div class="tp-caption   tp-resizeme" id="slide-44-layer-1" data-x="['<?= $slider->position ?>','<?= $slider->position ?>','center','center']" data-hoffset="['0','100','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-55','-55','-55','-40']" data-fontsize="['72','72','62','45']" data-lineheight="['82','82','72','55']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1080,"split":"chars","splitdelay":0.1,"speed":1500,"split_direction":"forward","frame":"0","from":"sX:0.8;sY:0.8;opacity:0;","to":"o:1;","ease":"Power4.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 72px; line-height: 82px; font-weight: 500; color:black; letter-spacing: 0px;font-family:Poppins;"><span class="drk-blu"><?= $slider->medicalname ?></span>
                                <!-- <span class="light-blu">Health</span>  -->
                            </div>

                            <!-- LAYER NR. 3 -->
                            <div class="tp-caption   tp-resizeme" id="slide-44-layer-3" data-x="['<?= $slider->position ?>','<?= $slider->position ?>','center','center']" data-hoffset="['0','100','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['40','53','53','60']" data-width="['600','600','600','450']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; text-align:right !important; min-width: 600px; max-width: 600px; white-space: normal; font-size: 16px; line-height: 26px; font-weight: 400; color:black; letter-spacing: 0px;font-family:Roboto;"><?= $slider->content ?> </div>

                            <!-- LAYER NR. 4 -->
                            <div class="tp-caption  tp-resizeme" id="slide-44-layer-4" data-x="['<?= $slider->position ?>','<?= $slider->position ?>','center','center']" data-hoffset="['0','100','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['138','138','138','180']" data-width="['600','600','600','450']" data-height="none" data-whitespace="normal" data-type="button" data-responsive_offset="on" data-frames='[{"delay":3350,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[<?php if ($slider->position == 'right') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "450";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "0";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } ?>,0,0,0]" style="z-index: 8; font-family:Roboto;"><a href="<?= $slider->buttonurl ?>" class="btn btn-rounded btn-large btn-blue"><?= $slider->buttonlabel ?></a></div>
                        <?php endif; ?>
                        <?php if ($key % 2 == 1) : ?>
                            <div class="tp-caption   tp-resizeme" id="slide-45-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-120','-120','-120','-96']" data-fontsize="['36','36','28','23']" data-lineheight="['46','46','38','33']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":270,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 36px; line-height: 46px; font-weight: 500; color: #484b59; letter-spacing: 0px;font-family:Poppins; "><?= $slider->medicalname ?> </div>

                            <!-- LAYER NR. 6 -->
                            <div class="tp-caption   tp-resizeme" id="slide-45-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-55','-55','-55','-40']" data-fontsize="['72','72','62','45']" data-lineheight="['82','82','72','55']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1080,"split":"chars","splitdelay":0.1,"speed":1500,"split_direction":"forward","frame":"0","from":"sX:0.8;sY:0.8;opacity:0;","to":"o:1;","ease":"Power4.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 72px; line-height: 82px; font-weight: 500; color: #484b59; letter-spacing: 0px;font-family:Poppins;"><span class="drk-blu">
                                    <?= $slider->medicalname ?>


                                </span> </div>

                            <!-- LAYER NR. 7 -->
                            <div class="tp-caption   tp-resizeme" id="slide-45-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['40','53','53','60']" data-width="['600','600','600','450']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; min-width: 600px; max-width: 600px; white-space: normal; font-size: 16px; line-height: 26px; font-weight: 400; color: #797979; letter-spacing: 0px;font-family:Roboto; "><?= $slider->content ?> </div>

                            <!-- LAYER NR. 8 -->
                            <div class="tp-caption   tp-resizeme" id="slide-45-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['138','138','138','180']" data-width="['600','600','600','450']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":3350,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; font-family:Roboto; "><a href="<?= $slider->buttonurl ?>" class="btn btn-rounded btn-large btn-blue"><?= $slider->buttonlabel ?></a></div>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
        </div>
    </div>